# Oauth client configuration specifics
config:
  clientID: "oauth2-proxy"
  clientSecret: "jlfa14HlYOmqeAdXZyfMSWl50Fd96pkf"
  # Create a new secret with the following command
  # openssl rand -base64 32 | head -c 32 | base64
  cookieSecret: "NXA4K2lMUGsrSnFLYnprWnZESE5GUDNINzIrc2NHUnQ="
  configFile: |-
    provider = "oidc"
    provider_display_name = "Keycloak"
    oidc_issuer_url = "https://sso.ssotest.perelle.com/auth/realms/Business"
    email_domains = [ "*" ]
    scope = "openid profile email"
    cookie_domains = ".ssotest.perelle.com"
    whitelist_domains = ".ssotest.perelle.com"
    pass_authorization_header = true
    pass_access_token = true
    pass_user_headers = true
    set_authorization_header = true
    set_xauthrequest = true
    cookie_refresh = "1m"
    cookie_expire = "30m"

ingress:
  enabled: true
  path: /
  hosts:
    - oauth.ssotest.perelle.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
  tls:
    - secretName: oauth-proxy-tls
      hosts:
        - oauth.ssotest.perelle.com